### ISSUE TITLE
Anagrams faster version is looks slower

### ISSUE THREAD

**Issue by shubham8111** [chiphuyen/coding-exercises#4]
I am using below function to test performance of two functions, the faster one is actually taking almost twice more time. Any comments?

def time_test():
	A = ""
	B = ""
	for x in range(1000000):
		A = A + random.choice(string.ascii_letters)
		B = B + random.choice(string.ascii_letters)
	
	A_shuff = list(A)
	random.shuffle(A_shuff)
	A_shuff = "".join(A_shuff)

	s = time.clock()
	are_anagrams(A, A_shuff)
	e = time.clock()
	print("slow", e -s)
	s = time.clock()
	are_anagrams_fast(A, A_shuff)
	e = time.clock()
	print("fast", e -s)
	s = time.clock()
	are_anagrams(A, B)
	e = time.clock()
	print("slow", e -s)
	s = time.clock()
	are_anagrams_fast(A, B)
	e = time.clock()
	print("fast", e -s)

=================================================
slow 0.15625
fast 0.359375
slow 0.140625
fast 0.34375

**Comment by chiphuyen** [comment]
You're right. are_anagrams_fast is faster for strings of about 100 characters, then it gets worse. I clearly (and idiotically) underestimated the built-in implementation of Counter. I've updated the file. Thank you!
